version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
      args:
        VARIANT: 14
        USER_UID: 1000
        USER_GID: 1000
    ports:
      - 3000:3000
    # expose:
    # - 3000
    networks:
      - bridge

    volumes:
      - ..:/workspace:cached
    # - ..:/usr/src/app/

    # Overrides default command so things don't shut down after the process ends.
    # command: . bin/db-init.sh
    command: sleep infinity
    #    command: yarn start

    env_file:
      - ../.env.local

    # network_mode: service:db
    depends_on:
      - db

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/  # this will persist data beyond the life of the container
    ports:
      - 5432:5432
    networks:
      - bridge
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
networks:
  bridge:
volumes:
  postgres-data:
