# This is only for the development environment to facilitate VS Code / Docker integration
ARG VARIANT=12
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

# Update args in docker-compose.yaml to set the UID/GID of the "node" user.
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN if [ "$USER_GID" != "1000" ] || [ "$USER_UID" != "1000" ]; then groupmod --gid $USER_GID node && usermod --uid $USER_UID --gid $USER_GID node; fi

LABEL author="Philip Spelman"

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ARG NODE_VERSION='14.15.5'
ARG NVM_DIR=/root
ARG NVM_VERSION='v0.37.2'
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get -y upgrade \
    && apt-get -y install --no-install-recommends \
    apt-utils \
    bash-completion \
    build-essential \
    cron \
    curl \
    gcc \
    git \
    htop \
    libpq-dev \
    nano \
    netcat \
    openssh-client \
    postgresql-client \
    sudo \
    vim \
    && rm -rf /var/cache/apt-get/* \
    && rm -rf /var/lib/apt/lists/*


# Install NVM and desired version of Node
RUN curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh" | bash \
    && source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION

# Update args in docker-compose.yaml to set the UID/GID of the "vscode" user.
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN if [ "$USER_GID" != "1000" ] || [ "$USER_UID" != "1000" ]; then groupmod --gid $USER_GID vscode && usermod --uid $USER_UID --gid $USER_GID vscode; fi

WORKDIR /workspace

# Copy React API project's requirements
COPY ./package.json /workspace/package.json
COPY / /workspace/
RUN ls -la /workspace/*

# BUILD the app
RUN ["yarn", "install"]
RUN ["yarn", "build"]

COPY . /workspace/

ENV PORT=3000
#EXPOSE 3000

COPY ./env-init.sh /

RUN chmod +x /env-init.sh

COPY ./start.sh /
RUN chmod +x /start.sh

COPY ./entrypoint.dev.sh /
RUN chmod +x /entrypoint.dev.sh

ENTRYPOINT ["/entrypoint.dev.sh"]

EXPOSE 3000

CMD ["yarn", "start"]

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1

#CMD ["yarn", "start"]
