version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:index
    depends_on:
      - index

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  index:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:

services:
  web:
    build:
      context: ..
      dockerfile: .vscontainer/Dockerfile
    #      dockerfile: ""
    volumes:
      - ..:/usr/src/app/
      - ..:/home/slycr:cached
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      DJANGO_SUPERUSER_USERNAME: vs_dev
      DJANGO_SUPERUSER_PASSWORD: vaporstream
      DJANGO_SUPERUSER_EMAIL: vs_dev@vaporstream.com
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # this will persist data beyond the life of the container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
